All tests are done
Aleechetorres/reto_3_automationTesting pull request #1
Opened 2023-08-16 21:54 UTC by Aleechetorres

2023-08-16 23:36 UTC, DanielCalleCO requested changes
Borra las dos carpetas de pruebas default que trae cypress `1-getting-started` y `2-advanced-examples` corrige el último test y aprobamos!

2023-08-16 23:36 UTC, DanielCalleCO commented on cypress/e2e/testHotels.cy.js
> +
AquÍ te recomiendo primero activar un filtro, para luego verificar que el botón clear funciona.. porque en realidad el sitio muestra las mismas cards que si le damos clear, lo que no nos garantiza el correcto funcionamiento del botón... 

Imagina que si el boton no sirve, igual, cuando cargue la página, viene con los 18 hotels.. igual el test va a pasar, lo que no nos sirve...

2023-08-16 23:36 UTC, DanielCalleCO commented on cypress/fixtures/example.json
Este archivo también lo puedes borrar

2023-08-18 13:09 UTC, Aleechetorres commented on cypress/e2e/testHotels.cy.js
> +
Hola dani, se implemento la activación del filtro de pais. Se suben cambios. Se borraron también las carpetas sugeridas

2023-08-18 13:09 UTC, Aleechetorres commented on cypress/fixtures/example.json
Se borró el archivo y se subieron cambios

2023-08-18 14:16 UTC, DanielCalleCO approved these changes
Buen trabajo Ale! Ya puedes desproteger main si quieres seguir subiendo cositas a este repo!

2023-08-29 20:47 UTC, merged